### ISSUE TITLE
Notifications don't appear in apps built with JUCE 

### ISSUE THREAD

**Issue by tommaisey** [Ableton/LinkKit#45]
We're currently implementing Link in our app built with JUCE. Everything's looking good, but we're not seeing in-app notifications. I'm not sure where to start with finding out why.

It may be useful to refer to the [JUCE code](https://github.com/WeAreROLI/JUCE/blob/master/modules/juce_gui_basics/native/juce_ios_UIViewComponentPeer.mm) that wraps iOS native windows.

I should note that we work closely with the JUCE team closely, so we can expedite any changes required.

**Comment by romancfischer** [comment]
@fgo-ableton 
I don't use JUCE but have implement Ableton Link inside a framework which resides inside two AUv3 extensions ( effect and instrument ). The notifications don't show up there either.

First I wouldn't have access to **UIApplication.sharedApplication.delegate.window** because of the following error message:
_'sharedApplication' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead._

This can be fixed by turning **Require Only App-Extensions-Safe API** inside the frameworks build settings to **No**

So I ran a test like that:

`if let window = UIApplication.shared.delegate?.window{
     /* present some view controller.. */
}`

It compiles but it doesn't show anything..

It would be great if you could add an option, to set a view to draw the notifications onto instead.

**Comment by fgo-ableton** [comment]
Hmm. Passing a pointer is kind of tricky too: This would require to set the view whenever a background window is available, set it to something else when the view changes, and reset it to nil when the app goes to background.
That sounds like a scenario that could quite easily cause crashes.
That plus the Swift/Objective C complication make me think that maybe the most solid route here is to use the C API from https://github.com/ableton/link/ and directly draw the notifications in Swift yourself?

**Comment by designerfuzzi** [comment]
I see nothing wrong with posting a NSNotification aka CFNotification that could be defined and as such registered to be Observed. After all NSNotifications is a String based mechanism for good reason, because it allows to hook up into NSNotifcationCenter by just knowing the string. When the post mechanism is done properly it can also be send on main thread, as normal send Notifications cause the observer to run linked functions in the thread they where send. Dispatch is the key..

**Comment by rororomeda** [comment]
@fgo-ableton 
I understand.
The Link C Library doesn't give me access to ABLLinkSettingsViewController, right? Because that's a LinkKit-only thing, as far as I can see?

Am I correct to assume that the only callback I need in order to draw the notifications myself is: **setNumPeersCallback()**
Could you make this one available in LinkKit as well? That would probably be the easiest and most flexible solution for everyone.

**Comment by rororomeda** [comment]
I have created a pull request:
https://github.com/Ableton/LinkKit/pull/69

**Comment by fgo-ableton** [comment]
@rororomeda Thanks for the PR! I'm not so happy with adding the callback setter to the API and not showing the default notification based on that. This is a bit confusing. We did not add the numPeers property to the LinkKit API as it should not be needed for the general use case and I'd prefer to leave it this way.
I pushed a different approach here: https://github.com/Ableton/LinkKit/tree/peers-notification
There is now a `NSNotification` with the key `ABLLink.NumberOfPeersChanged` to observe the number of peers. When listening to the notification the user setting to enable/disable notifications should also be checked (see the example in the last commit). I also added a plist key `ABLLinkSuppressNotifications` to prevent LinkKit from showing the default notification.

**Comment by rororomeda** [comment]
@fgo-ableton 
Thanks, that's cool with me.
I built your branch and included it in my project. It works very well.

My last request would be to ask you for a new release with the new changes so I can submit my app to the App Store with the appropriate LinkKit licence : )

**Comment by fgo-ableton** [comment]
I just uploaded a new release: https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.10
